### ISSUE TITLE
你好，请问那个身份证的45字符在哪查看得到？

### ISSUE THREAD

**Issue by zengAlex** [kagurazakakotori/damai-script#1]

**Comment by kagurazakakotori** [comment]
![screenshot](http://wx3.sinaimg.cn/large/69e35d32gy1foq7a5ai2aj21kw0yptek.jpg)
在“实名证件信息”-“选择购票人”界面中，对单选框进行审查元素，其中的"realname_cardid"属性即为身份证45字符

**Comment by zengAlex** [comment]
我已经实名认证过了，就没有这个选项了

**Comment by zengAlex** [comment]
我这边有个问题，就是这个开票时间直接转成时间戳就可以了吧？

**Comment by kagurazakakotori** [comment]
是的，转成时间戳即可，单位为毫秒

**Comment by galaxy24** [comment]
你好，请问大麦网自动填写订单信息怎么没能自动选择实名证件信息？提交身份证的那个脚本

**Comment by Cheese-Yu** [comment]
@galaxy24 地址变了，脚本注释第十行的地址换成 // @match *://buy.damai.cn/*  就可以了。

**Comment by kagurazakakotori** [comment]
请自行解决

galaxy24 <notifications@github.com>于2018年3月24日周六 下午4:22写道：
